# Generated by Django 3.0.3 on 2020-02-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
