# Generated by Django 3.0.3 on 2020-02-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_editor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='no image found', upload_to='articles/'),
        ),
    ]
